#name: Jenkins Deploy on Tag Release
#
#on:      
# release:
#    types:
#      - created
#    
#jobs:
#  jenkins-pipeline:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#        
#      - name: Trigger Jenkins Job
#        env:
#          JENKINS_URL: ${{ secrets.JENKINS_URL }}
#          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
#          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
#          JOB_NAME: 'deploy_pipeline' #Get from env?
#        run: |
#          curl -X POST -u "${JENKINS_USERNAME}:${JENKINS_API_TOKEN}" \
#            "${JENKINS_URL}job/${JOB_NAME}/buildWithParameters?TAG=${{ github.ref }}"
        
  
